[package]
name = "train"
version = "0.1.0"
edition = "2024"

[dependencies]
shared_lib = { path = "../shared_lib" }
csv = "1.4.0"
plotters = "0.3.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
owo-colors = "4.2.3"
